### PR TITLE
lib: archive kdump.conf and content of kdump initramfs

### LINKED ISSUE #42: task: archive the file list in kdump.img for each test
Before triggering a crash, log the file list of kdump.img.
`lsinitrd` could do the job.

### PR DESCRIPTION
**Pull request by sztsian**
Fixes #42

Signed-off-by: Ziqian SUN <zsun@redhat.com>

### CODE REVIEW

File: lib/kdump.sh [hunk 1]
```diff
@@ -52,10 +57,29 @@ prepare_env()
         echo "--$i--" >> ${K_HWINFO_FILE}
         ethtool -i $i >> ${K_HWINFO_FILE}
     done
-
     report_file "${K_HWINFO_FILE}"
 }
 
+collect_lsinitrd()
+{
+    INITRAMFS_SUFFIX="`uname -r`kdump.img"
```
Comment (emmawu) [inline lib/kdump.sh]: pls use INITRAMFS_SUFFIX="$(uname -r)kdump.img"

File: lib/kdump.sh [hunk 2]
```diff
@@ -52,10 +57,29 @@ prepare_env()
...
+    INITRAMFS_NAME=`ls /boot | grep ${INITRAMFS_SUFFIX}`
```
Comment (emmawu) [inline lib/kdump.sh]: pls use $() instead of ``

File: lib/kdump.sh [hunk 3]
```diff
@@ -52,10 +57,29 @@ prepare_env()
...
+    lsinitrd /boot/${INITRAMFS_NAME} >> ${K_INITRAMFS_LIST}
+    report_file "${K_INITRAMFS_LIST}"
+}
+
+# Upload Current system information
+# Including:
+#   Upload hardware info
+#   Upload kdump config
+#   Upload file list of initramfs
+upload_currentinfo()
```
Comment (emmawu) [inline lib/kdump.sh]: feel better to name method as report_system_info()

File: lib/kdump.sh [hunk 4]
```diff
@@ -38,6 +39,10 @@ prepare_env()
 {
     mkdir -p "${K_BACKUP_DIR}"
     cp /etc/kdump.conf "${K_BACKUP_DIR}"/
+}
+
+collect_hwinfo()
```
Comment (emmawu) [inline lib/kdump.sh]: feel better to rename method as report_hwinfo()

File: lib/kdump.sh [hunk 5]
```diff
@@ -13,6 +13,7 @@ K_CONFIG="/etc/kdump.conf"
 K_DEFAULT_PATH="/var/crash"
 K_SSH_CONFIG="${HOME}/.ssh/config"
 K_HWINFO_FILE="/tmp/hwinfo.log"
+K_INITRAMFS_LIST="/tmp/initramfs.list"
```
Comment (emmawu) [inline lib/kdump.sh]: Is that possible to store all system info files in a sub-directory under /tmp? e.g /tmp/sysinfo/
because we may need to run clean up task between tests. and all those data should be removed before running of next test. it's easier to erase all files under a directory.

Comment (sztsian) [inline lib/kdump.sh]: I am thinking about this just now. Feeling that it would be a complex check somewhere. Will figure out later

File: lib/kdump.sh [hunk 6]
```diff
@@ -52,10 +61,29 @@ prepare_env()
         echo "--$i--" >> ${K_HWINFO_FILE}
```
Comment (emmawu) [inline lib/kdump.sh]: tab...the indentation...
