### PR TITLE
:bug: Use lib function to make ko in crash-altsysrq-c

### LINKED ISSUE #28: bug: crash-altsysrq-c should replace load_altsysrq_driver() with lib method kdump.make_module()
kdump library already has a method **make_module()** to compile .c to .ko.
But in **crash-altsysrq-c** test, we have another method **load_altsysrq_drive()** which does exact same thing as make_module() except it install the module at the end. 

We should always re-use lib method if we can.

### PR DESCRIPTION
**Pull request by sztsian**
Fixes #28
Replace load_altsysrq_driver() in crash-altsysrq-c with library method
kdump.make_module() in crash-altsysrq-c

Signed-off-by: Zamir SUN <sztsian@gmail.com>

### CODE REVIEW

File: crash-altsysrq-c/runtest.sh [hunk 1]
```diff
@@ -24,25 +24,13 @@
...
-}
-
 crash_altsysrq_c()
 {
     if [ ! -f ${C_REBOOT} ]; then
         kdump_prepare
         kdump_restart
-        load_altsysrq_driver
+        make_module "altsysrq"
+        insmod ./altsysrq.ko || log_error "- Fail to insmod altsysrq"
```
Comment (emmawu) [inline crash-altsysrq-c/runtest.sh]: The module should be at altsysrq/altsysrq.ko, right ? It's in a sub-directory.
